### ISSUE TITLE
Sample project doesn't build?

### ISSUE THREAD

**Issue by rscott78** [andyfmiller/LtiSamples#1]
I'm trying to figure out where to start digging into this. I'd like to create my own Lti provider, so I figured I'd start with the sample project. I downloaded it and the LitLibrary project from Github. 

If I build the entire solution, I get dozens of errors, but since I'm only interested in the Provider, I'm trying to build that - I get a single error, it's complaining about a missing definition for "ChallengeResultUrl" - line 177 of Startup.Auth.cs.

It feels like the source is out of date on GitHub perhaps.. is there something I'm missing?

**Comment by andyfmiller** [comment]
The source on GitHub is not out of date exactly, but it is in transition. I'm adding Outcomes V2 and that created a naming/namespace problem. I decided to move Basic Outcomes (aka Outcomes V1) to the LtiLibrary.Core.Outcomes.v1 namespace, and put Outcomes V2 in LtiLibrary.Core.Outcomes.v2. 

I'm only part way through that process and unfortunately, the Provider and Consumer projects no longer build. However, I just posted an update to the SimpleLti project so that it builds and runs correctly.

Until I get everything straightened out on GitHub, you might like the code on CodePlex better. I will not be updating CodePlex any more (all the new stuff will go here in GitHub), but it is very stable.

http://ltisamples.codeplex.com/

It is also the code that is running on Azure web sites:

http://consumer.azurewebsites.net/
http://provider.azurewebsites.net/

And it is the code that corresponds to LtiLibrary 1.4.5 on Nuget,

http://www.nuget.org/packages/LtiLibrary/
